apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: c01
    image: centos
    command: ["/bin/bash", "-c", "sleep 1000"]
    volumeMounts:
    - name: testvolume
      mountPath: /tmp/contdir
  volumes:
  - name: testvolume
    hostPath:
      path: /tmp/hostdir
