kind: Pod
apiVersion: v1
metadata:
  name: labelspod1
  labels:
    day: fri
    class: kubernetes

spec:
  containers:
    - name: resource
      image: centos
      command: ['/bin/bash', '-c', 'while true; do echo Hi-Gowdre; sleep 5; done']
